name: Build Release Tar

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build linux/amd64 output tar
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          outputs: type=docker,dest=./antrack-web-amd64.tar

      - name: Build linux/arm64 output tar
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          outputs: type=docker,dest=./antrack-web-arm64.tar

      - name: Create Release & Upload tar files
        uses: softprops/action-gh-release@v2
        with:
          name: AntRack Release ${{ github.ref_name }}
          body: |
            ## 版本说明
            - antrack-web-amd64.tar ：x86_64 Ubuntu服务器使用
            - antrack-web-arm64.tar：ARM64开发板（RK、树莓派等）使用
            
            使用方式：
            ```bash
            docker load -i xxx.tar
            docker compose up -d
